// Code Generated by Sidekick is for learning and experimentation purposes only.

/** @type {import('jest'). Config} */

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      tsconfig: {
        target: 'ES2020',
        lib: ['ES2020', 'DOM'],
        module: 'commonjs',
        moduleResolution: 'node',
        jsx: 'react-jsx',
        esModuleInterop: true,
        skipLibCheck: true,
        isolatedModules: false,
        types: ['jest', 'testing-library__jest-dom', 'node'],
      }
    }],
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    '^@/(.*)$': '<rootDir>/$1',
  },
  // This is the critical line!
  moduleDirectories: ['node_modules', '<rootDir>/'],
};
