// Code Generated by Sidekick is for learning and experimentation purposes only.
// components/ExchangeMap.tsx
import React, { useMemo, useState } from "react";
import { EXCHANGE_SERVERS } from "../data/exchanges";
import { PlottableExchange, toPlottableExchanges } from "./mapAdapters";

type Props = {
  onSelect?: (id: string | null) => void;
  selectedId?: string | null;
};

type Provider = "AWS" | "GCP" | "Azure";

function getProviderColor(p: Provider): string {
  switch (p) {
    case "AWS":
      return "#bb8009"; // orange/yellow
    case "GCP":
      return "#1f6feb"; // blue
    case "Azure":
      return "#2ea043"; // teal/green
    default:
      return "#ccc";
  }
}

export default function ExchangeMap({ onSelect, selectedId }: Props) {
  const [hovered, setHovered] = useState<PlottableExchange | null>(null);
  const width = 900;
  const height = 460;

  const nodes: PlottableExchange[] = useMemo(() => {
    return toPlottableExchanges(EXCHANGE_SERVERS, width, height);
  }, [width, height]);

  return (
    <div style={{ position: "relative" }}>
      <svg
        width={width}
        height={height}
        role="img"
        aria-label="Exchange server locations"
        style={{ background: "#0d1117", borderRadius: 8 }}
      >
        {/* Render markers */}
        {nodes.map((s) => {
          const color = getProviderColor(s.provider);
          const selected = selectedId === s.id;
          const size = selected ? 8 : 5;

          return (
            <g
              key={s.id}
              transform={`translate(${s.x}, ${s.y})`}
              onMouseEnter={() => setHovered(s)}
              onMouseLeave={() => setHovered((curr) => (curr?.id === s.id ? null : curr))}
              onClick={() => onSelect?.(selected ? null : s.id)}
              style={{ cursor: "pointer" }}
            >
              {s.provider === "AWS" && <circle r={size} fill={color} />}
              {s.provider === "GCP" && (
                <rect x={-size} y={-size} width={size * 2} height={size * 2} fill={color} />
              )}
              {s.provider === "Azure" && (
                <polygon points={`0,${-size} ${size},0 0,${size} ${-size},0`} fill={color} />
              )}
              {selected && <circle r={size + 3} stroke={color} fill="none" strokeWidth={1.5} />}
            </g>
          );
        })}
      </svg>

      {/* Hover Tooltip */}
      {hovered && (
        <div
          role="tooltip"
          style={{
            position: "absolute",
            left: hovered.x + 12,
            top: hovered.y + 12,
            padding: "8px 10px",
            borderRadius: 6,
            border: "1px solid rgba(255,255,255,0.08)",
            background: "rgba(13,17,23,0.95)",
            color: "#ddd",
            fontSize: 12,
            pointerEvents: "none",
            maxWidth: 240
          }}
        >
          <div style={{ fontWeight: 600 }}>{hovered.name}</div>
          <div style={{ opacity: 0.8 }}>
            {hovered.city ? `${hovered.city}` : ""}
            {hovered.city && (hovered.region || hovered.country) ? ", " : ""}
            {hovered.region ?? hovered.country ?? ""}
          </div>
          <div style={{ opacity: 0.8 }}>Provider: {hovered.provider}</div>
          <div style={{ opacity: 0.8 }}>
            Coords: {hovered.latitude.toFixed(2)}, {hovered.longitude.toFixed(2)}
          </div>
        </div>
      )}
    </div>
  );
}
