// Code Generated by Sidekick is for learning and experimentation purposes only.
// components/LatencyTrendChart.tsx
import React, { useMemo } from "react";
import { LatencyPoint } from "./LatencyStats";

type Props = {
  points: LatencyPoint[];
  width?: number;
  height?: number;
};

export default function LatencyTrendChart({ points, width = 640, height = 220 }: Props) {
  const padding = { top: 10, right: 16, bottom: 24, left: 40 };

  const { path, xTicks, yTicks } = useMemo(() => {
    if (!points.length) return { path: "", xTicks: [], yTicks: [] };

    const xs = points.map((p) => p.ts);
    const ys = points.map((p) => p.ms);

    const xMin = Math.min(...xs);
    const xMax = Math.max(...xs);
    const yMin = Math.min(...ys);
    const yMax = Math.max(...ys);

    const iw = width - padding.left - padding.right;
    const ih = height - padding.top - padding.bottom;

    const xScale = (x: number) =>
      padding.left + ((x - xMin) / (xMax - xMin || 1)) * iw;
    const yScale = (y: number) =>
      padding.top + (1 - (y - yMin) / (yMax - yMin || 1)) * ih;

    let d = "";
    points
      .sort((a, b) => a.ts - b.ts)
      .forEach((p, i) => {
        const X = xScale(p.ts);
        const Y = yScale(p.ms);
        d += i === 0 ? `M ${X} ${Y}` : ` L ${X} ${Y}`;
      });

    // naive ticks
    const xTicks = [
      { x: xScale(xMin), label: new Date(xMin).toLocaleTimeString() },
      { x: xScale(xMax), label: new Date(xMax).toLocaleTimeString() }
    ];
    const yTicks = [
      { y: yScale(yMin), label: `${Math.round(yMin)} ms` },
      { y: yScale(yMax), label: `${Math.round(yMax)} ms` }
    ];

    return { path: d, xTicks, yTicks };
  }, [points, width, height]);

  return (
    <svg width={width} height={height} role="img" aria-label="Latency trend">
      {/* Axes */}
      <line
        x1={padding.left}
        y1={height - padding.bottom}
        x2={width - padding.right}
        y2={height - padding.bottom}
        stroke="rgba(255,255,255,0.2)"
      />
      <line
        x1={padding.left}
        y1={padding.top}
        x2={padding.left}
        y2={height - padding.bottom}
        stroke="rgba(255,255,255,0.2)"
      />

      {/* Trend path */}
      <path d={path} stroke="#1f6feb" strokeWidth={1.5} fill="none" />

      {/* Ticks */}
      {xTicks.map((t, i) => (
        <g key={i} transform={`translate(${t.x}, ${height - padding.bottom})`}>
          <line y2="6" stroke="rgba(255,255,255,0.2)" />
          <text y="18" fill="#ddd" fontSize="11" textAnchor="middle">
            {t.label}
          </text>
        </g>
      ))}
      {yTicks.map((t, i) => (
        <g key={i} transform={`translate(${padding.left}, ${t.y})`}>
          <line x2="-6" stroke="rgba(255,255,255,0.2)" />
          <text x="-10" fill="#ddd" fontSize="11" textAnchor="end" dominantBaseline="middle">
            {t.label}
          </text>
        </g>
      ))}
    </svg>
  );
}
