// Code Generated by Sidekick is for learning and experimentation purposes only.
// components/mapAdapters.ts
import { ExchangeServer } from "../data/exchanges";

export type PlottableExchange = {
  id: string;
  name: string;
  provider: "AWS" | "GCP" | "Azure";
  city?: string;
  region?: string;
  country?: string; // optional; only present if your data includes it
  latitude: number;
  longitude: number;
  x: number;
  y: number;
};

// Simple equirectangular projection; replace if you have a map library
export function project(lat: number, lon: number, w: number, h: number) {
  const x = ((lon + 180) / 360) * w;
  const y = ((90 - lat) / 180) * h;
  return { x, y };
}

export function toPlottableExchanges(
  servers: ExchangeServer[],
  width: number,
  height: number
): PlottableExchange[] {
  // Only include servers that actually have lat/lon values
  return servers
    .filter((s) => typeof (s as any).latitude === "number" && typeof (s as any).longitude === "number")
    .map((s) => {
      const lat = (s as any).latitude as number;
      const lon = (s as any).longitude as number;
      const { x, y } = project(lat, lon, width, height);
      return {
        id: s.id,
        name: s.name,
        provider: s.provider as "AWS" | "GCP" | "Azure",
        city: (s as any).city,
        region: (s as any).region,
        country: (s as any).country, // may be undefined
        latitude: lat,
        longitude: lon,
        x,
        y
      };
    });
}
