// Code Generated by Sidekick is for learning and experimentation purposes only.
// components/ProviderLegend.tsx
import React from "react";

export default function ProviderLegend() {
  return (
    <div
      aria-label="Provider legend"
      style={{
        marginTop: 8,
        padding: "8px 10px",
        borderRadius: 6,
        border: "1px solid rgba(255,255,255,0.08)",
        background: "rgba(13,17,23,0.6)",
        color: "#ddd",
        fontSize: 12,
        width: "fit-content"
      }}
    >
      <div style={{ fontWeight: 600, marginBottom: 6 }}>Legend</div>
      <div style={{ display: "grid", gap: 6 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <svg width="18" height="18">
            <circle cx="9" cy="9" r="5" fill="#bb8009" />
          </svg>
          <span>AWS-hosted exchange</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <svg width="18" height="18">
            <rect x="4" y="4" width="10" height="10" fill="#1f6feb" />
          </svg>
          <span>GCP-hosted exchange</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <svg width="18" height="18">
            <polygon points="9,3 15,9 9,15 3,9" fill="#2ea043" />
          </svg>
          <span>Azure-hosted exchange</span>
        </div>
      </div>
    </div>
  );
}
