// Code Generated by Sidekick is for learning and experimentation purposes only.
// components/TrendControls.tsx
import React, { useMemo } from "react";
import { EXCHANGE_SERVERS, ExchangeServer } from "../data/exchanges";

export type TimeRangeKey = "1h" | "24h" | "7d" | "30d";

type Props = {
  selectedFrom: string | null;
  selectedTo: string | null;
  selectedRegion: string | null;
  timeRange: TimeRangeKey;
  onChangePair: (fromId: string | null, toId: string | null) => void;
  onChangeRegion: (region: string | null) => void;
  onChangeTimeRange: (range: TimeRangeKey) => void;
};

export default function TrendControls({
  selectedFrom,
  selectedTo,
  selectedRegion,
  timeRange,
  onChangePair,
  onChangeRegion,
  onChangeTimeRange
}: Props) {
  const regions = useMemo(() => {
    const set = new Set<string>();
    EXCHANGE_SERVERS.forEach((s) => set.add(s.region));
    return Array.from(set).sort();
  }, []);

  return (
    <div style={{ display: "grid", gap: 12 }}>
      <div>
        <strong>Select Pair</strong>
        <div style={{ display: "grid", gap: 8, gridTemplateColumns: "1fr 1fr" }}>
          <select
            aria-label="From exchange"
            value={selectedFrom ?? ""}
            onChange={(e) => onChangePair(e.target.value || null, selectedTo)}
          >
            <option value="">(Any)</option>
            {EXCHANGE_SERVERS.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name} — {s.region}
              </option>
            ))}
          </select>

          <select
            aria-label="To exchange"
            value={selectedTo ?? ""}
            onChange={(e) => onChangePair(selectedFrom, e.target.value || null)}
          >
            <option value="">(Any)</option>
            {EXCHANGE_SERVERS.map((s) => (
              <option key={s.id} value={s.id}>
                {s.name} — {s.region}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div>
        <strong>Filter by Region</strong>
        <select
          aria-label="Region filter"
          value={selectedRegion ?? ""}
          onChange={(e) => onChangeRegion(e.target.value || null)}
        >
          <option value="">(All regions)</option>
          {regions.map((r) => (
            <option key={r} value={r}>
              {r}
            </option>
          ))}
        </select>
      </div>

      <div>
        <strong>Time Range</strong>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          {(["1h", "24h", "7d", "30d"] as TimeRangeKey[]).map((r) => (
            <button
              key={r}
              aria-pressed={timeRange === r}
              onClick={() => onChangeTimeRange(r)}
              style={{
                fontSize: 12,
                padding: "4px 8px",
                borderRadius: 6,
                background: timeRange === r ? "#1f6feb" : "transparent",
                color: timeRange === r ? "#fff" : "#ddd",
                border: "1px solid rgba(255,255,255,0.2)",
                cursor: "pointer"
              }}
            >
              {r}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
