// Code Generated by Sidekick is for learning and experimentation purposes only.
// utils/exportCsv.ts
export function toCsv(rows: Record<string, string | number | null | undefined>[]): string {
    if (!rows.length) return "";
    const headers = Object.keys(rows[0]);
    const esc = (val: unknown) => {
      if (val === null || val === undefined) return "";
      const s = String(val);
      if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
      return s;
    };
    const head = headers.map(esc).join(",");
    const body = rows.map((r) => headers.map((h) => esc(r[h])).join(",")).join("\n");
    return `${head}\n${body}`;
  }
  
  export function downloadTextFile(filename: string, content: string, mime = "text/csv;charset=utf-8") {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }
  