// Code Generated by Sidekick is for learning and experimentation purposes only.
/**
 * exchange.ts
 * Canonical types and seed data for exchange servers.
 */

export type Provider = "AWS" | "GCP" | "Azure";

export type ExchangeServer = {
  id: string;
  name: string;
  provider: Provider;
  region: string;
  latitude: number;
  longitude: number;
  city?: string;
  /**
   * Optional: URLs to probe for demo RTT using latencyapi.com (Path A).
   * If provided, latencyProvider will try these before synthetic latency.
   */
  probes?: string[];
};

export const EXCHANGE_SERVERS: ExchangeServer[] = [
  // Americas (East)
  {
    id: "coinbase-us-east",
    name: "Coinbase",
    provider: "AWS",
    region: "us-east-1",
    latitude: 40.7128, // New York
    longitude: -74.0060,
    city: "New York",
    probes: ["https://www.coinbase.com"]
  },
  {
    id: "kraken-us-east",
    name: "Kraken",
    provider: "GCP",
    region: "us-east1",
    latitude: 38.9072, // Washington DC area
    longitude: -77.0369,
    city: "Washington, D.C.",
    probes: ["https://www.kraken.com"]
  },

  // Americas (Central/West)
  {
    id: "coinbase-us-west",
    name: "Coinbase West",
    provider: "AWS",
    region: "us-west-2",
    latitude: 37.7749, // San Francisco
    longitude: -122.4194,
    city: "San Francisco",
    probes: ["https://www.coinbase.com"]
  },
  {
    id: "binance-us-west",
    name: "Binance US West",
    provider: "Azure",
    region: "westus2",
    latitude: 47.6062, // Seattle
    longitude: -122.3321,
    city: "Seattle",
    probes: ["https://www.binance.us"]
  },

  // Europe
  {
    id: "binance-eu-frankfurt",
    name: "Binance EU",
    provider: "AWS",
    region: "eu-central-1",
    latitude: 50.1109,
    longitude: 8.6821,
    city: "Frankfurt",
    probes: ["https://www.binance.com"]
  },
  {
    id: "kraken-eu-fra",
    name: "Kraken EU",
    provider: "GCP",
    region: "europe-west3",
    latitude: 50.1109,
    longitude: 8.6821,
    city: "Frankfurt",
    probes: ["https://www.kraken.com"]
  },
  {
    id: "deribit-ams",
    name: "Deribit",
    provider: "Azure",
    region: "westeurope",
    latitude: 52.3702,
    longitude: 4.8952,
    city: "Amsterdam",
    probes: ["https://www.deribit.com"]
  },
  {
    id: "bitstamp-lon",
    name: "Bitstamp",
    provider: "AWS",
    region: "eu-west-2",
    latitude: 51.5074,
    longitude: -0.1278,
    city: "London",
    probes: ["https://www.bitstamp.net"]
  },
  {
    id: "coinbase-eu-dublin",
    name: "Coinbase EU",
    provider: "AWS",
    region: "eu-west-1",
    latitude: 53.3498,
    longitude: -6.2603,
    city: "Dublin",
    probes: ["https://www.coinbase.com"]
  },

  // Middle East
  {
    id: "binance-bah",
    name: "Binance MENA",
    provider: "Azure",
    region: "uaenorth",
    latitude: 25.2048, // Dubai
    longitude: 55.2708,
    city: "Dubai",
    probes: ["https://www.binance.com"]
  },

  // Asia (East)
  {
    id: "okx-hk",
    name: "OKX",
    provider: "GCP",
    region: "asia-east2",
    latitude: 22.3193,
    longitude: 114.1694,
    city: "Hong Kong",
    probes: ["https://www.okx.com"]
  },
  {
    id: "bitflyer-tokyo",
    name: "bitFlyer",
    provider: "AWS",
    region: "ap-northeast-1",
    latitude: 35.6762,
    longitude: 139.6503,
    city: "Tokyo",
    probes: ["https://bitflyer.com"]
  },
  {
    id: "binance-tokyo",
    name: "Binance JP",
    provider: "Azure",
    region: "japaneast",
    latitude: 35.6762,
    longitude: 139.6503,
    city: "Tokyo",
    probes: ["https://www.binance.com"]
  },

  // Asia (Southeast)
  {
    id: "binance-sg",
    name: "Binance",
    provider: "AWS",
    region: "ap-southeast-1",
    latitude: 1.3521,
    longitude: 103.8198,
    city: "Singapore",
    probes: ["https://www.binance.com"]
  },
  {
    id: "okx-sg",
    name: "OKX",
    provider: "GCP",
    region: "asia-southeast1",
    latitude: 1.2833,
    longitude: 103.8333,
    city: "Singapore",
    probes: ["https://www.okx.com"]
  },
  {
    id: "bybit-sg",
    name: "Bybit",
    provider: "Azure",
    region: "southeastasia",
    latitude: 1.2903,
    longitude: 103.8519,
    city: "Singapore",
    probes: ["https://www.bybit.com"]
  },

  // Asia (South)
  {
    id: "wazirx-mumbai",
    name: "WazirX",
    provider: "AWS",
    region: "ap-south-1",
    latitude: 19.0760,
    longitude: 72.8777,
    city: "Mumbai",
    probes: ["https://wazirx.com"]
  },

  // Oceania
  {
    id: "independentreserve-sydney",
    name: "Independent Reserve",
    provider: "AWS",
    region: "ap-southeast-2",
    latitude:  -33.8688,
    longitude: 151.2093,
    city: "Sydney",
    probes: ["https://www.independentreserve.com"]
  },

  // Americas (South)
  {
    id: "mercadobitcoin-sp",
    name: "Mercado Bitcoin",
    provider: "GCP",
    region: "southamerica-east1",
    latitude: -23.5505,
    longitude: -46.6333,
    city: "São Paulo",
    probes: ["https://www.mercadobitcoin.com.br"]
  },

  // Africa
  {
    id: "luno-johannesburg",
    name: "Luno",
    provider: "Azure",
    region: "southafricanorth",
    latitude: -26.2041,
    longitude: 28.0473,
    city: "Johannesburg",
    probes: ["https://www.luno.com"]
  }
];

/**
 * Fast lookup map for id -> ExchangeServer
 */
export const EXCHANGE_BY_ID: Map<string, ExchangeServer> = new Map(
  EXCHANGE_SERVERS.map((s) => [s.id, s])
);
