// Code Generated by Sidekick is for learning and experimentation purposes only.
// pages/topology.tsx
import React, { useState } from "react";
import ControlsPanel from "../components/ControlsPanel";
import ExchangeMap from "../components/ExchangeMap";
import ProviderLegend from "../components/ProviderLegend";
import { Provider } from "../data/exchanges";

export default function TopologyPage() {
  const [selectedExchange, setSelectedExchange] = useState<string | null>(null);
  const [providers, setProviders] = useState<Record<string, boolean>>({
    AWS: true,
    GCP: true,
    Azure: true
  });

  const toggleProvider = (p: Provider) => {
    setProviders((prev) => ({ ...prev, [p]: !prev[p] }));
  };

  return (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 300px", gap: 16 }}>
      <div>
        <ExchangeMap onSelect={setSelectedExchange} selectedId={selectedExchange} />
        <ProviderLegend />
      </div>
      <div>
        <ControlsPanel
          providers={providers}
          onToggleProvider={toggleProvider}
          onSelectExchange={setSelectedExchange}
          selectedExchange={selectedExchange}
          onSearch={() => {}}
        />
      </div>
    </div>
  );
}
